on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push to main branch
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-interaction
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: twireless.ng
        username: ${{ secrets.TWIRELESS_FTP_USERNAME }}
        password: ${{ secrets.TWIRELESS_FTP_PASSWORD }}
        server-dir: public_html/